<?php
/**
* @file
* A description of what your module does.
*/

use Drupal\node\Entity\Node;

/**
 * Implements hook_theme().
 */
function mfasiri_interface_theme($existing, $type, $theme, $path)
{
    $interpretor_platform = Node::load(8);
    $translation = Drupal::service('entity.repository')->getTranslationFromContext($interpretor_platform);
    return [
      'mfasiri_homepage' => [
          'variables' => [
              'platform_node' => $translation,
          ],
      ],
    ];
}