<?php
/**
* @file
* A description of what your module does.
*/

use Drupal\node\Entity\Node;

/**
 * Implements hook_theme().
 */
function mfasiri_interface_theme($existing, $type, $theme, $path)
{
//    $langcode = Drupal::languageManager()->getLanguage(\Drupal\Core\Language\Language::TYPE_CONTENT)->getId();
//    $langcode = Drupal::languageManager()->getCurrentLanguage()->getId();
    $interpretor_platform = Node::load(8);

    $translation = Drupal::service('entity.repository')->getTranslationFromContext($interpretor_platform);
    return [
      'mfasiri_homepage' => [
          'variables' => [
//              'platform_node' => $interpretor_platform->getTranslation($langcode),
              'platform_node' => $translation,
          ],
      ],
    ];
}